"""2FA, Budget-Verteilungsprofile, Szenario-Detailregeln

Revision: 60e901723c70
Vorgänger: b0df6edd43c2
Erstellt: 2026-08-06 07:24:34.264607
"""
from alembic import op
import sqlalchemy as sa


revision = '60e901723c70'
down_revision = 'b0df6edd43c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('szenario_regeln',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('szenario_id', sa.Integer(), nullable=False),
    sa.Column('konto_id', sa.Integer(), nullable=True),
    sa.Column('gruppe_id', sa.Integer(), nullable=True),
    sa.Column('faktor', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['gruppe_id'], ['konto_gruppen.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['konto_id'], ['konten.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['szenario_id'], ['szenarien.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('szenario_regeln', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_szenario_regeln_szenario_id'), ['szenario_id'], unique=False)

    # server_default, damit bestehende Zeilen beim ALTER gefüllt werden
    with op.batch_alter_table('benutzer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_geheimnis', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('totp_aktiv', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))
        batch_op.add_column(sa.Column('totp_letzter_schritt', sa.Integer(), nullable=False,
                                      server_default='0'))

    with op.batch_alter_table('konten', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verteilung', sa.String(length=16), nullable=False,
                                      server_default='GLEICH'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('konten', schema=None) as batch_op:
        batch_op.drop_column('verteilung')

    with op.batch_alter_table('benutzer', schema=None) as batch_op:
        batch_op.drop_column('totp_letzter_schritt')
        batch_op.drop_column('totp_aktiv')
        batch_op.drop_column('totp_geheimnis')

    with op.batch_alter_table('szenario_regeln', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_szenario_regeln_szenario_id'))

    op.drop_table('szenario_regeln')
    # ### end Alembic commands ###
