"""Basisschema

Revision: 8014e2975ebc
Vorgänger: 
Erstellt: 2026-08-06 06:34:11.122854
"""
from alembic import op
import sqlalchemy as sa


revision = '8014e2975ebc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benutzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('passwort_hash', sa.String(length=512), nullable=False),
    sa.Column('rolle', sa.String(length=20), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('benutzer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benutzer_email'), ['email'], unique=True)

    op.create_table('mandanten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kurzname', sa.String(length=64), nullable=False),
    sa.Column('kontenrahmen', sa.String(length=16), nullable=False),
    sa.Column('bundesland', sa.String(length=2), nullable=False),
    sa.Column('ust_zeitraum', sa.String(length=10), nullable=False),
    sa.Column('dauerfrist', sa.Boolean(), nullable=False),
    sa.Column('verfahrensstatus', sa.String(length=32), nullable=False),
    sa.Column('aktenzeichen', sa.String(length=64), nullable=True),
    sa.Column('insolvenz_stichtag', sa.Date(), nullable=True),
    sa.Column('insolvenzgeld_aktiv', sa.Boolean(), nullable=False),
    sa.Column('insolvenzgeld_von', sa.Date(), nullable=True),
    sa.Column('insolvenzgeld_bis', sa.Date(), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kurzname')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benutzer_id', sa.Integer(), nullable=True),
    sa.Column('mandant_id', sa.Integer(), nullable=True),
    sa.Column('aktion', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('zeit', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], ),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benutzer_mandanten',
    sa.Column('benutzer_id', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('benutzer_id', 'mandant_id')
    )
    op.create_table('bwa_werte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.Integer(), nullable=False),
    sa.Column('konto_nr', sa.String(length=16), nullable=False),
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('monat', sa.Integer(), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandant_id', 'konto_nr', 'jahr', 'monat')
    )
    with op.batch_alter_table('bwa_werte', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bwa_werte_mandant_id'), ['mandant_id'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.Integer(), nullable=False),
    sa.Column('dateiname', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('anzahl', sa.Integer(), nullable=False),
    sa.Column('warnungen', sa.Text(), nullable=True),
    sa.Column('benutzer_id', sa.Integer(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], ),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_mandant_id'), ['mandant_id'], unique=False)

    op.create_table('konto_gruppen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('richtung', sa.String(length=10), nullable=False),
    sa.Column('sortierung', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['konto_gruppen.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandant_id', 'code')
    )
    with op.batch_alter_table('konto_gruppen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_konto_gruppen_mandant_id'), ['mandant_id'], unique=False)

    op.create_table('plan_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.Integer(), nullable=False),
    sa.Column('stichtag', sa.Date(), nullable=False),
    sa.Column('wochen', sa.Integer(), nullable=False),
    sa.Column('kommentar', sa.String(length=255), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_snapshots_mandant_id'), ['mandant_id'], unique=False)

    op.create_table('szenarien',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kommentar', sa.String(length=255), nullable=True),
    sa.Column('ein_faktor', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('aus_faktor', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('debitoren_verzoegerung_tage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('szenarien', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_szenarien_mandant_id'), ['mandant_id'], unique=False)

    op.create_table('buchungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('konto_nr', sa.String(length=16), nullable=False),
    sa.Column('gegenkonto_nr', sa.String(length=16), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sh', sa.String(length=1), nullable=False),
    sa.Column('belegfeld', sa.String(length=64), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buchungen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buchungen_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buchungen_datum'), ['datum'], unique=False)
        batch_op.create_index(batch_op.f('ix_buchungen_gegenkonto_nr'), ['gegenkonto_nr'], unique=False)
        batch_op.create_index(batch_op.f('ix_buchungen_konto_nr'), ['konto_nr'], unique=False)
        batch_op.create_index(batch_op.f('ix_buchungen_mandant_id'), ['mandant_id'], unique=False)

    op.create_table('konten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.Integer(), nullable=False),
    sa.Column('nummer', sa.String(length=16), nullable=False),
    sa.Column('bezeichnung', sa.String(length=255), nullable=False),
    sa.Column('typ', sa.String(length=20), nullable=False),
    sa.Column('ust_satz', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gruppe_id', sa.Integer(), nullable=True),
    sa.Column('kreditlinie', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('liquiditaetswirksam', sa.Boolean(), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gruppe_id'], ['konto_gruppen.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandant_id', 'nummer')
    )
    with op.batch_alter_table('konten', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_konten_mandant_id'), ['mandant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_konten_nummer'), ['nummer'], unique=False)

    op.create_table('bestaende',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=10), nullable=False),
    sa.Column('konto_id', sa.Integer(), nullable=True),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('wert', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['konto_id'], ['konten.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bestaende', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bestaende_datum'), ['datum'], unique=False)
        batch_op.create_index(batch_op.f('ix_bestaende_mandant_id'), ['mandant_id'], unique=False)

    op.create_table('budget_wochen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.Integer(), nullable=False),
    sa.Column('konto_id', sa.Integer(), nullable=False),
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('kw', sa.Integer(), nullable=False),
    sa.Column('betrag_netto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['konto_id'], ['konten.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandant_id', 'konto_id', 'jahr', 'kw')
    )
    with op.batch_alter_table('budget_wochen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_wochen_konto_id'), ['konto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_wochen_mandant_id'), ['mandant_id'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.Integer(), nullable=False),
    sa.Column('konto_id', sa.Integer(), nullable=False),
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('monat', sa.Integer(), nullable=False),
    sa.Column('betrag_netto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['konto_id'], ['konten.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandant_id', 'konto_id', 'jahr', 'monat')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_konto_id'), ['konto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_mandant_id'), ['mandant_id'], unique=False)

    op.create_table('dauerbuchungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('art', sa.String(length=10), nullable=False),
    sa.Column('konto_id', sa.Integer(), nullable=True),
    sa.Column('betrag_brutto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('intervall', sa.String(length=16), nullable=False),
    sa.Column('stichtag', sa.Integer(), nullable=False),
    sa.Column('gueltig_von', sa.Date(), nullable=False),
    sa.Column('gueltig_bis', sa.Date(), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['konto_id'], ['konten.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dauerbuchungen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dauerbuchungen_mandant_id'), ['mandant_id'], unique=False)

    op.create_table('offene_posten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.Integer(), nullable=False),
    sa.Column('art', sa.String(length=10), nullable=False),
    sa.Column('partner', sa.String(length=255), nullable=False),
    sa.Column('belegnr', sa.String(length=64), nullable=True),
    sa.Column('rechnungsdatum', sa.Date(), nullable=True),
    sa.Column('faellig_am', sa.Date(), nullable=False),
    sa.Column('zahlung_geplant_am', sa.Date(), nullable=True),
    sa.Column('betrag_brutto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bezahlt_betrag', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('konto_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('bezahlt_am', sa.Date(), nullable=True),
    sa.Column('forderungsklasse', sa.String(length=32), nullable=True),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['konto_id'], ['konten.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offene_posten', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offene_posten_faellig_am'), ['faellig_am'], unique=False)
        batch_op.create_index(batch_op.f('ix_offene_posten_mandant_id'), ['mandant_id'], unique=False)

    op.create_table('plan_snapshot_werte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('konto_id', sa.Integer(), nullable=True),
    sa.Column('termin_typ', sa.String(length=16), nullable=True),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['konto_id'], ['konten.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['plan_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_snapshot_werte', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_snapshot_werte_datum'), ['datum'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_snapshot_werte_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('termin_regeln',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=16), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('betrag_modus', sa.String(length=10), nullable=False),
    sa.Column('betrag_fix', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('konto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['konto_id'], ['konten.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandant_id', 'typ')
    )
    with op.batch_alter_table('termin_regeln', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_termin_regeln_mandant_id'), ['mandant_id'], unique=False)

    op.create_table('zahlungstermine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=16), nullable=False),
    sa.Column('periode', sa.String(length=16), nullable=True),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('konto_id', sa.Integer(), nullable=True),
    sa.Column('kommentar', sa.String(length=255), nullable=True),
    sa.Column('generiert', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['konto_id'], ['konten.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zahlungstermine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zahlungstermine_datum'), ['datum'], unique=False)
        batch_op.create_index(batch_op.f('ix_zahlungstermine_mandant_id'), ['mandant_id'], unique=False)

    op.create_table('bank_transaktionen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('konto_id', sa.Integer(), nullable=False),
    sa.Column('buchungstag', sa.Date(), nullable=False),
    sa.Column('valuta', sa.Date(), nullable=True),
    sa.Column('betrag', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('partner', sa.String(length=255), nullable=True),
    sa.Column('verwendungszweck', sa.Text(), nullable=True),
    sa.Column('referenz', sa.String(length=64), nullable=True),
    sa.Column('posten_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['konto_id'], ['konten.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['posten_id'], ['offene_posten.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_transaktionen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_transaktionen_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transaktionen_buchungstag'), ['buchungstag'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transaktionen_konto_id'), ['konto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transaktionen_mandant_id'), ['mandant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transaktionen_posten_id'), ['posten_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transaktionen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_transaktionen_posten_id'))
        batch_op.drop_index(batch_op.f('ix_bank_transaktionen_mandant_id'))
        batch_op.drop_index(batch_op.f('ix_bank_transaktionen_konto_id'))
        batch_op.drop_index(batch_op.f('ix_bank_transaktionen_buchungstag'))
        batch_op.drop_index(batch_op.f('ix_bank_transaktionen_batch_id'))

    op.drop_table('bank_transaktionen')
    with op.batch_alter_table('zahlungstermine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zahlungstermine_mandant_id'))
        batch_op.drop_index(batch_op.f('ix_zahlungstermine_datum'))

    op.drop_table('zahlungstermine')
    with op.batch_alter_table('termin_regeln', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_termin_regeln_mandant_id'))

    op.drop_table('termin_regeln')
    with op.batch_alter_table('plan_snapshot_werte', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_snapshot_werte_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_plan_snapshot_werte_datum'))

    op.drop_table('plan_snapshot_werte')
    with op.batch_alter_table('offene_posten', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offene_posten_mandant_id'))
        batch_op.drop_index(batch_op.f('ix_offene_posten_faellig_am'))

    op.drop_table('offene_posten')
    with op.batch_alter_table('dauerbuchungen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dauerbuchungen_mandant_id'))

    op.drop_table('dauerbuchungen')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_mandant_id'))
        batch_op.drop_index(batch_op.f('ix_budgets_konto_id'))

    op.drop_table('budgets')
    with op.batch_alter_table('budget_wochen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_wochen_mandant_id'))
        batch_op.drop_index(batch_op.f('ix_budget_wochen_konto_id'))

    op.drop_table('budget_wochen')
    with op.batch_alter_table('bestaende', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bestaende_mandant_id'))
        batch_op.drop_index(batch_op.f('ix_bestaende_datum'))

    op.drop_table('bestaende')
    with op.batch_alter_table('konten', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_konten_nummer'))
        batch_op.drop_index(batch_op.f('ix_konten_mandant_id'))

    op.drop_table('konten')
    with op.batch_alter_table('buchungen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buchungen_mandant_id'))
        batch_op.drop_index(batch_op.f('ix_buchungen_konto_nr'))
        batch_op.drop_index(batch_op.f('ix_buchungen_gegenkonto_nr'))
        batch_op.drop_index(batch_op.f('ix_buchungen_datum'))
        batch_op.drop_index(batch_op.f('ix_buchungen_batch_id'))

    op.drop_table('buchungen')
    with op.batch_alter_table('szenarien', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_szenarien_mandant_id'))

    op.drop_table('szenarien')
    with op.batch_alter_table('plan_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_snapshots_mandant_id'))

    op.drop_table('plan_snapshots')
    with op.batch_alter_table('konto_gruppen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_konto_gruppen_mandant_id'))

    op.drop_table('konto_gruppen')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_mandant_id'))

    op.drop_table('import_batches')
    with op.batch_alter_table('bwa_werte', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bwa_werte_mandant_id'))

    op.drop_table('bwa_werte')
    op.drop_table('benutzer_mandanten')
    op.drop_table('audit_log')
    op.drop_table('mandanten')
    with op.batch_alter_table('benutzer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benutzer_email'))

    op.drop_table('benutzer')
    # ### end Alembic commands ###
