"""OP-Ausgleich als Zuordnungstabelle (n:m für Sammelüberweisungen)

Bestehende 1:1-Verknüpfungen (bank_transaktionen.posten_id) werden als
Zuordnungen mit dem vollen Umsatzbetrag übernommen, danach entfällt die Spalte.

Revision: b0df6edd43c2
Vorgänger: 8014e2975ebc
Erstellt: 2026-08-06 06:44:39.667664
"""
from alembic import op
import sqlalchemy as sa


revision = 'b0df6edd43c2'
down_revision = '8014e2975ebc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ausgleich_zuordnungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.Integer(), nullable=False),
    sa.Column('transaktion_id', sa.Integer(), nullable=False),
    sa.Column('posten_id', sa.Integer(), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandanten.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['posten_id'], ['offene_posten.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaktion_id'], ['bank_transaktionen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ausgleich_zuordnungen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ausgleich_zuordnungen_mandant_id'), ['mandant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ausgleich_zuordnungen_posten_id'), ['posten_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ausgleich_zuordnungen_transaktion_id'), ['transaktion_id'], unique=False)

    # Bestehende 1:1-Verknüpfungen als Zuordnungen übernehmen
    op.execute(
        """
        INSERT INTO ausgleich_zuordnungen
            (mandant_id, transaktion_id, posten_id, betrag, erstellt_am)
        SELECT bt.mandant_id, bt.id, bt.posten_id, ABS(bt.betrag), CURRENT_TIMESTAMP
        FROM bank_transaktionen bt
        WHERE bt.posten_id IS NOT NULL
        """
    )

    with op.batch_alter_table('bank_transaktionen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_transaktionen_posten_id'))
        # Der Fremdschlüssel fällt mit der Spalte (PostgreSQL: DROP COLUMN
        # entfernt abhängige Constraints; SQLite: Batch-Mode baut die Tabelle neu)
        batch_op.drop_column('posten_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transaktionen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posten_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(
            'fk_bank_transaktionen_posten_id', 'offene_posten',
            ['posten_id'], ['id'], ondelete='SET NULL',
        )
        batch_op.create_index(batch_op.f('ix_bank_transaktionen_posten_id'), ['posten_id'], unique=False)

    with op.batch_alter_table('ausgleich_zuordnungen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ausgleich_zuordnungen_transaktion_id'))
        batch_op.drop_index(batch_op.f('ix_ausgleich_zuordnungen_posten_id'))
        batch_op.drop_index(batch_op.f('ix_ausgleich_zuordnungen_mandant_id'))

    op.drop_table('ausgleich_zuordnungen')
    # ### end Alembic commands ###
